#include "serialize/math.hpp"
#include "serialize/serialize.hpp"

SERIALIZE_ENABLE()

DECL_PRIMITIVE_SERIALIZER_OPT(bool)
DECL_PRIMITIVE_SERIALIZER_OPT(char)

DECL_PRIMITIVE_SERIALIZER_OPT(u8)
DECL_PRIMITIVE_SERIALIZER_OPT(u16)
DECL_PRIMITIVE_SERIALIZER_OPT(u32)
DECL_PRIMITIVE_SERIALIZER_OPT(u64)
DECL_PRIMITIVE_SERIALIZER_OPT(u128)
DECL_PRIMITIVE_SERIALIZER_OPT(usize)

DECL_PRIMITIVE_SERIALIZER_OPT(i8)
DECL_PRIMITIVE_SERIALIZER_OPT(i16)
DECL_PRIMITIVE_SERIALIZER_OPT(i32)
DECL_PRIMITIVE_SERIALIZER_OPT(i64)
DECL_PRIMITIVE_SERIALIZER_OPT(i128)
DECL_PRIMITIVE_SERIALIZER_OPT(isize)

DECL_PRIMITIVE_SERIALIZER_OPT(f32)
DECL_PRIMITIVE_SERIALIZER_OPT(f64)

DECL_PRIMITIVE_SERIALIZER_OPT(math::vec2)
DECL_PRIMITIVE_SERIALIZER_OPT(math::vec3)
DECL_PRIMITIVE_SERIALIZER_OPT(math::vec4)

DECL_PRIMITIVE_SERIALIZER_OPT(math::ivec2)
DECL_PRIMITIVE_SERIALIZER_OPT(math::ivec3)
DECL_PRIMITIVE_SERIALIZER_OPT(math::ivec4)

DECL_PRIMITIVE_SERIALIZER_OPT(math::uvec2)
DECL_PRIMITIVE_SERIALIZER_OPT(math::uvec3)
DECL_PRIMITIVE_SERIALIZER_OPT(math::uvec4)

DECL_PRIMITIVE_SERIALIZER_OPT(math::bvec2)
DECL_PRIMITIVE_SERIALIZER_OPT(math::bvec3)
DECL_PRIMITIVE_SERIALIZER_OPT(math::bvec4)
